const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const {webcrypto} = require('node:crypto');
const ctx = vm.createContext({console,crypto:webcrypto,TextEncoder,App:{sessao:{user:{id:'dono-a'}}}});
vm.runInContext(['js/bestiario.js','js/nuvem.js'].map(p=>fs.readFileSync(p,'utf8')).join('\n')+'\nglobalThis.api={Bestiario,Nuvem};',ctx);
const {Bestiario:B,Nuvem:N}=ctx.api;
const registro={source_key:'livro-10',name:'Criatura',element:'Sangue',vd:20,type:'Criatura',tags:['livro'],notes:'Fonte',image_file:'ficha.jpg'};
const arquivo={name:'ficha.jpg',size:100,type:'image/jpeg'};
assert.equal(B.prepararLote([arquivo],{version:1,creatures:[registro]}).length,1);
assert.throws(()=>B.prepararLote([],{version:1,creatures:[registro]}),/Imagem ausente/);
assert.throws(()=>B.prepararLote([arquivo],{version:1,creatures:[registro,registro]}),/repetido/);
assert.throws(()=>B.prepararLote([arquivo],{version:1,creatures:[{...registro,vd:-1}]}),/Metadados inválidos/);
assert.throws(()=>B.prepararLote([arquivo],{version:1,creatures:[{...registro,source_key:'../arquivo'}]}),/Identificador/);
(async()=>{
 const registros=new Map();let uploads=0;
 N.cliente={from:()=>({select:()=>({eq:(_,id)=>({maybeSingle:async()=>({data:registros.get(id)||null})})})})};
 N.criarCriatura=async campos=>{uploads++;registros.set(campos.id,campos);return campos;};
 const a=await N.importarCriatura(registro,arquivo);
 assert.equal(a.existente,false);
 assert.match(a.criatura.id,/^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-a[0-9a-f]{3}-[0-9a-f]{12}$/);
 assert.equal((await N.importarCriatura(registro,arquivo)).existente,true);
 assert.equal(uploads,1);
 const revisado=await N.importarCriatura({...registro,image_revision:2},arquivo);
 assert.equal(revisado.atualizado,true);assert.equal(revisado.criatura.id,a.criatura.id);
 assert.equal((await N.importarCriatura({...registro,image_revision:2},arquivo)).atualizado,undefined);
 assert.equal(uploads,2);
 ctx.App.sessao.user.id='dono-b';
 const b=await N.importarCriatura(registro,arquivo);
 assert.notEqual(a.criatura.id,b.criatura.id);
 assert.equal(uploads,3);
 console.log('Lote: validação de arquivos, metadados, retomada sem duplicatas e separação por dono passaram.');
})().catch(e=>{console.error(e);process.exitCode=1;});
