const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const ctx=vm.createContext({console});
vm.runInContext(['js/dados.js','js/store.js','js/regras.js'].map(p=>readFileSync(p,'utf8')).join('\n')+'\nfunction num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d;}\nglobalThis.api={Regras,calcularStatus,CLASSE_INFO,ORIGENS,ORIGEM_INFO,Store,ajusteIdade};',ctx);
const {Regras:R,calcularStatus:C,CLASSE_INFO,ORIGENS,ORIGEM_INFO,Store,ajusteIdade}=ctx.api;
const attrs={AGI:2,FOR:1,INT:2,PRE:2,VIG:2};
const stat=(cl,nex)=>JSON.parse(JSON.stringify(C(cl,nex,attrs)));
assert.deepEqual(stat('Combatente',5),{pv:22,pe:4,san:12});
assert.deepEqual(stat('Combatente',99),{pv:136,pe:80,san:69});
assert.equal(C('Combatente',99,attrs).pv-C('Combatente',95,attrs).pv,6);
assert.equal(C('Sobrevivente',0,attrs,5).pv,18);
assert.equal(C('Sobrevivente',0,attrs,5).pe,8);
assert.equal(C('Sobrevivente',0,attrs,5).san,16);
assert.equal(C('Mundano',0,attrs).pe,3);
assert.equal(CLASSE_INFO.Ocultista.obrigatorias.length,2);
assert.equal(ORIGENS.length,46);
assert.equal(ORIGEM_INFO.Lutador.pericias,'Luta e Reflexos');
assert.deepEqual(Array.from(R.origemFixas('Chef')),['fortitude','profissao']);
assert.deepEqual(Array.from(R.origemFixas('Profetizado')),['vontade']);
assert.equal(R.status({classe:'Ocultista',origem:'Cultista Arrependido',nex:10,attrs}).san,15);
assert.equal(R.status({classe:'Combatente',origem:'Desgarrado',nex:99,attrs}).pv,156);
assert.equal(R.status({classe:'Sobrevivente',origem:'Mergulhador',nex:0,estagio:3,trilha:'Durão',attrs}).pv,25);
assert.equal(R.limitePE({classe:'Ocultista',origem:'Universitário',nex:99}),21);
assert.equal(R.equipamento({classe:'Combatente',patente:'Recruta',attrs:{FOR:0}}).cargaMax,2);
assert.equal(R.equipamento({classe:'Sobrevivente',attrs}).limites.I,1);
assert.equal(R.equipamento({classe:'Combatente',patente:'Agente Especial',origem:'Magnata',attrs}).credito,'Alto');
assert.equal(ajusteIdade({nex:99,desvantagensIdade:['fragil']}).pv,-40);
const ficha=Store.normalizar({id:'legada',classe:'Sobrevivente',pv:{atual:12,max:33},trilha:'Esperto',estagio:4});
assert.equal(ficha.pv.max,33);assert.equal(ficha.estagio,4);
assert.equal(R.habilidadesIniciais({classe:'Especialista',origem:'Policial',perito:['crime','investigacao']}).length,3);
console.log('Regras: 23 verificações passaram.');
