create table if not exists public.poderes_catalogo (
  id bigint generated by default as identity primary key,
  nome text not null,
  classe text not null,
  descricao text not null,
  livro text not null,
  pagina text not null,
  unique (nome, classe, livro)
);
alter table public.poderes_catalogo enable row level security;
drop policy if exists "Poderes visíveis para usuários autenticados" on public.poderes_catalogo;
create policy "Poderes visíveis para usuários autenticados" on public.poderes_catalogo for select to authenticated using (true);
